// This file was auto-generated by ML.NET Model Builder. 

using CatOD2_CodeGen;
using Microsoft.ML.Data;

// Create single instance of sample data from first line of dataset for model input.
var image = MLImage.CreateFromFile(@"C:\dev\datasets\StopSignSmall\free-to-use-sounds-Vkt3uDeDkdg-unsplash.jpg");
CatOD2.ModelInput sampleData = new CatOD2.ModelInput()
{
    Image = image,
};
// Make a single prediction on the sample data and print results.
var predictionResult = CatOD2.Predict(sampleData);
Console.WriteLine("\n\nPredicted Boxes:\n");
Console.WriteLine(string.Join(", ", predictionResult.PredictedBoundingBoxes));
Console.WriteLine($"\n\n score:{string.Join(", ", predictionResult.Score)}");

